/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Tipografia.JCFuente;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import javax.swing.JTable;


/**
 *
 * @author frans
 */
public class JDAnalizador extends javax.swing.JDialog {

    /**
     * Creates new form Compilador
     */
    JCFuente tipo;
    
    public JDAnalizador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        txtIngreso.setBorder(null);
        /*txtIngreso.setBackground(new Color(0, 0, 0, 10));
        txtIngreso.setForeground(Color.BLACK);*/
        
        tipo = new JCFuente();
        Titulo.setFont(tipo.fuente(tipo.ki, 0, 77));
        t2.setFont(tipo.fuente(tipo.cor, 1, 30));//cor pr re
        t1.setFont(tipo.fuente(tipo.cor, 1, 30));
        //jlResul.setFont(tipo.fuente(tipo.cor, 1, 25));
        //jtfRespuesta.setFont(tipo.fuente(tipo.cor, 1, 45));
        
        JTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        JTable.getTableHeader().setOpaque(false);
        JTable.getTableHeader().setBackground(new Color(32,136,203));
        JTable.getTableHeader().setForeground(new Color(255,255,255));
        JTable.setRowHeight(45);
        
        
    }
    
    class JPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int heigth = getHeight();
            
            //Color color1 = new Color(52,143,80);
            Color color1 = new Color(255,255,255);
            //Color color2 = new Color(86,180,211);
            Color color2 = new Color(255,255,255);
            GradientPaint gp = new GradientPaint (0,0, color1,180,heigth,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, heigth);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correcto = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        txtIngreso = new javax.swing.JTextArea();
        btnCreditos = new javax.swing.JButton();
        sResutado = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jlResul = new javax.swing.JLabel();
        jtfRespuesta = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnArchivo = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        t2 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();

        correcto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/correcto.png"))); // NOI18N

        error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/error.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/SalirG.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 650, 150, 130));

        txtIngreso.setBackground(new java.awt.Color(255, 255, 255));
        txtIngreso.setColumns(20);
        txtIngreso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtIngreso.setRows(1);
        txtIngreso.setToolTipText("");
        txtIngreso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIngreso.setCaretColor(new java.awt.Color(225, 225, 225));
        scroll.setViewportView(txtIngreso);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 410, 60));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/EquipoP.png"))); // NOI18N
        btnCreditos.setBorder(null);
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.setFocusPainted(false);
        btnCreditos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/EquipoG.png"))); // NOI18N
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 110, 100));

        JTable.setBackground(new java.awt.Color(255, 255, 255));
        JTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTable.setForeground(new java.awt.Color(0, 0, 0));
        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Token", "Identificador"
            }
        ));
        JTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTable.setGridColor(new java.awt.Color(128, 128, 128));
        JTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        JTable.setMinimumSize(new java.awt.Dimension(25, 150));
        JTable.setRowHeight(20);
        JTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        JTable.setShowVerticalLines(false);
        JTable.getTableHeader().setReorderingAllowed(false);
        sResutado.setViewportView(JTable);

        getContentPane().add(sResutado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, 260));

        jlResul.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlResul.setText("Resultado:");
        getContentPane().add(jlResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jtfRespuesta.setEditable(false);
        jtfRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        jtfRespuesta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtfRespuesta.setBorder(null);
        getContentPane().add(jtfRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 250, 50));

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/pdfP.png"))); // NOI18N
        btnPDF.setBorder(null);
        btnPDF.setBorderPainted(false);
        btnPDF.setContentAreaFilled(false);
        btnPDF.setEnabled(false);
        btnPDF.setFocusPainted(false);
        btnPDF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/pdfG.png"))); // NOI18N
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -20, 110, 100));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Analizador");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 340, 80));

        jSeparator1.setBackground(new java.awt.Color(247, 190, 190));
        jSeparator1.setForeground(new java.awt.Color(247, 190, 190));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 420, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Titulo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 421, 215));

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ArchivoP.png"))); // NOI18N
        btnArchivo.setBorder(null);
        btnArchivo.setBorderPainted(false);
        btnArchivo.setContentAreaFilled(false);
        btnArchivo.setFocusPainted(false);
        btnArchivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ArchivoG.png"))); // NOI18N
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -20, 110, 100));

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/AnalizadorP.png"))); // NOI18N
        btnAnalizar.setBorder(null);
        btnAnalizar.setBorderPainted(false);
        btnAnalizar.setContentAreaFilled(false);
        btnAnalizar.setFocusPainted(false);
        btnAnalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/AnalizadorG.png"))); // NOI18N
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 110, 100));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BorrarP.png"))); // NOI18N
        btnBorrar.setBorder(null);
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setFocusPainted(false);
        btnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BorrarG.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 110, 100));

        t2.setText(" Operacion:");
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        t1.setText("Ingrese la");
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        setBounds(0, 0, 1315, 786);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAnalizador dialog = new JDAnalizador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTable;
    private javax.swing.JLabel Titulo;
    public javax.swing.JButton btnAnalizar;
    public javax.swing.JButton btnArchivo;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnCreditos;
    public javax.swing.JButton btnPDF;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel correcto;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel jlResul;
    public javax.swing.JTextField jtfRespuesta;
    public javax.swing.JScrollPane sResutado;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    public javax.swing.JTextArea txtIngreso;
    // End of variables declaration//GEN-END:variables
}
