/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Tipografia.JCFuente;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author frans
 */
public class JDCompilador extends javax.swing.JDialog {

    /**
     * Creates new form Compilador
     */
    JCFuente tipo;
    
    public JDCompilador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        txtIngreso.setBorder(null);
        /*txtIngreso.setBackground(new Color(0, 0, 0, 10));
        txtIngreso.setForeground(Color.BLACK);*/
        
        tipo = new JCFuente();
        Titulo.setFont(tipo.fuente(tipo.ki, 0, 70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        txtIngreso = new javax.swing.JTextArea();
        btnCreditos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlResul = new javax.swing.JLabel();
        jtfRespuesta = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnArchivo = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/SalirG.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 572, 150, 130));

        txtIngreso.setBackground(new java.awt.Color(255, 255, 255));
        txtIngreso.setColumns(20);
        txtIngreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtIngreso.setRows(2);
        txtIngreso.setToolTipText("");
        txtIngreso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtIngreso.setCaretColor(new java.awt.Color(225, 225, 225));
        scroll.setViewportView(txtIngreso);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 470, 50));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/EquipoP.png"))); // NOI18N
        btnCreditos.setBorder(null);
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.setFocusPainted(false);
        btnCreditos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/EquipoG.png"))); // NOI18N
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Token", "Identificador"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 911, 195));

        jlResul.setText("Resultado:");
        getContentPane().add(jlResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jtfRespuesta.setEditable(false);
        getContentPane().add(jtfRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 74, -1));

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/pdfP.png"))); // NOI18N
        btnPDF.setBorder(null);
        btnPDF.setBorderPainted(false);
        btnPDF.setContentAreaFilled(false);
        btnPDF.setEnabled(false);
        btnPDF.setFocusPainted(false);
        btnPDF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/pdfG.png"))); // NOI18N
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 110, 100));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Compilador");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 310, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Titulo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 6, 421, 215));

        jSeparator1.setBackground(new java.awt.Color(247, 190, 190));
        jSeparator1.setForeground(new java.awt.Color(247, 190, 190));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 670, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese la Operacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ArchivoP.png"))); // NOI18N
        btnArchivo.setBorder(null);
        btnArchivo.setBorderPainted(false);
        btnArchivo.setContentAreaFilled(false);
        btnArchivo.setFocusPainted(false);
        btnArchivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ArchivoG.png"))); // NOI18N
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 100));

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/AnalizadorP.png"))); // NOI18N
        btnAnalizar.setBorder(null);
        btnAnalizar.setBorderPainted(false);
        btnAnalizar.setContentAreaFilled(false);
        btnAnalizar.setFocusPainted(false);
        btnAnalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/AnalizadorG.png"))); // NOI18N
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 110, 100));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BorrarP.png"))); // NOI18N
        btnBorrar.setBorder(null);
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setFocusPainted(false);
        btnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/BorrarG.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 110, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtIngreso.setText("");
        jtfRespuesta.setText("");
        jTable1.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCompilador dialog = new JDCompilador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    public javax.swing.JButton btnAnalizar;
    public javax.swing.JButton btnArchivo;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnPDF;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTable1;
    public javax.swing.JLabel jlResul;
    public javax.swing.JTextField jtfRespuesta;
    private javax.swing.JScrollPane scroll;
    public javax.swing.JTextArea txtIngreso;
    // End of variables declaration//GEN-END:variables
}
